[[pages]]
path = "Home.py"
name = "ãƒ›ãƒ¼ãƒ  / Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_user_preferences.py"
name = "åˆ©ç”¨è€…ï¼šå¸Œæœ›æ—¥å…¥åŠ› / User: Preferred dates"
icon = "ğŸ—“ï¸"

[[pages]]
path = "pages/2_user_events.py"
name = "åˆ©ç”¨è€…ï¼šã‚¤ãƒ™ãƒ³ãƒˆå…¥åŠ› / User: Events"
icon = "ğŸ«"

[[pages]]
path = "pages/3_results.py"
name = "çµæœã®è©³ç´°è¡¨ç¤º / Results"
icon = "ğŸ“Š"

[[pages]]
path = "pages/9_admin.py"
name = "ç®¡ç†è€…ï¼šè¨­å®šã¨å®Ÿè¡Œ / Admin"
icon = "ğŸ› ï¸"
